# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a095e9869d83335511e7bec1584e68d78cc216d44d0d4aaf3fc7dbd9399d2b921841cdb10c62b6e42e6a254940fa161e6b37ebc82badaeb2fc42fd315f0dbbb

test:
  secret_key_base: 3d55889b62e06326ca2a6b23b38fd2ed37f35e904db67cef72e9e475277b3acf7bff9febf58898a27e4d6129b0dac4d28f26528e8cf095e84b43aa153bfb0d00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
